services:
    benchmark.normalizer.user:
        class: PhpBenchmarksSymfony\Bundle\RestBundle\Normalizer\UserNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.normalizer.comment:
        class: PhpBenchmarksSymfony\Bundle\RestBundle\Normalizer\CommentNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.normalizer.comment_type:
        class: PhpBenchmarksSymfony\Bundle\RestBundle\Normalizer\CommentTypeNormalizer
        public: false
        arguments: ['@translator']
        tags:
            - { name: serializer.normalizer }

    benchmark.event_listener.define_locale:
        class: PhpBenchmarksSymfony\EventListener\DefineLocaleEventListener
        arguments: ['@request', '@translator']
        scope: request
        tags:
            - { name: kernel.event_listener, event: defineLocale }
