PhpBenchmarksSymfony\SmallOverloadBundle\Entity\SmallOverload99:
    type: entity
    table: small_overload_99

    id:
        id:
            type: integer
            generator: { strategy: AUTO }
            options: { unsigned: true }

    fields:
        date:
            type: date

        dateTime:
            type: datetime

        fixedString:
            type: string
            length: 31
            options:
                fixed: true

        variableString:
            type: string
            length: 255
